export const DEFAULT_CONFIG = {
  concurrency: 8,
  priorityThreshold: 0.3,
  customTitle: "",
  customDescription: "",
  includePaths: [] as string[],
  excludePaths: [] as string[],
  requestTimeout: 10000,
  userAgent: "Mozilla/5.0 (compatible; LLMS-txt-Generator/1.0)",
};

// Section categorization rules
export const SECTION_RULES = {
  home: ["", "home", "homepage", "index", "welcome", "start"],
  about: [
    "about",
    "about-us",
    "who-we-are",
    "company",
    "our-story",
    "team",
    "mission",
    "vision",
    "values",
  ],
  contact: [
    "contact",
    "contact-us",
    "support",
    "help",
    "get-in-touch",
    "customer-service",
    "assistance",
    "faq",
  ],
  services: [
    "services",
    "products",
    "offer",
    "pricing",
    "plans",
    "solutions",
    "features",
    "what-we-do",
  ],
  guides: [
    "guide",
    "guides",
    "tutorial",
    "tutorials",
    "how-to",
    "manual",
    "documentation",
    "docs",
    "setup",
    "walkthrough",
  ],
  blog: ["blog", "articles", "news", "updates", "press", "stories", "events"],
  reviews: [
    "reviews",
    "testimonials",
    "feedback",
    "opinions",
    "ratings",
    "experiences",
  ],
  insights: [
    "insights",
    "analysis",
    "research",
    "reports",
    "trends",
    "case-studies",
    "whitepapers",
  ],
  legal: [
    "privacy",
    "cookie",
    "terms",
    "legal",
    "gdpr",
    "privacy-policy",
    "tos",
    "terms-of-service",
    "terms-and-conditions",
    "disclaimer",
    "compliance",
    "security",
  ],
  resources: [
    "resources",
    "downloads",
    "download",
    "tools",
    "assets",
    "media",
    "templates",
    "forms",
    "brochures",
    "whitepaper",
  ],
};

export const SECTION_DISPLAY_NAMES = {
  home: "Main content",
  about: "About",
  contact: "Contacts",
  services: "Products and Services",
  guides: "Guides and Tutorials",
  blog: "Blog and Articles",
  reviews: "Reviews and Feedback",
  insights: "Insights and Research",
  legal: "Policies and Legal",
  resources: "Resources and Downloads",
  other: "Other Content",
};
